# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qsmackerJobsearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 446)
        self.qsmacker_jobname = QtWidgets.QTextEdit(Dialog)
        self.qsmacker_jobname.setGeometry(QtCore.QRect(20, 70, 181, 31))
        self.qsmacker_jobname.setObjectName("qsmacker_jobname")
        self.find_job_btn = QtWidgets.QPushButton(Dialog)
        self.find_job_btn.setGeometry(QtCore.QRect(120, 110, 81, 23))
        self.find_job_btn.setObjectName("find_job_btn")
        self.label_job = QtWidgets.QLabel(Dialog)
        self.label_job.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.label_job.setObjectName("label_job")
        self.batch_list = QtWidgets.QListWidget(Dialog)
        self.batch_list.setGeometry(QtCore.QRect(250, 110, 341, 201))
        self.batch_list.setObjectName("batch_list")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(260, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.job_id = QtWidgets.QLabel(Dialog)
        self.job_id.setGeometry(QtCore.QRect(260, 60, 47, 13))
        self.job_id.setObjectName("job_id")
        self.mac_total = QtWidgets.QLabel(Dialog)
        self.mac_total.setGeometry(QtCore.QRect(340, 60, 47, 13))
        self.mac_total.setObjectName("mac_total")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 40, 91, 16))
        self.label_5.setObjectName("label_5")
        self.com_total = QtWidgets.QLabel(Dialog)
        self.com_total.setGeometry(QtCore.QRect(440, 60, 47, 13))
        self.com_total.setObjectName("com_total")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(440, 40, 91, 16))
        self.label_7.setObjectName("label_7")
        self.kill_job_btn = QtWidgets.QPushButton(Dialog)
        self.kill_job_btn.setGeometry(QtCore.QRect(114, 140, 91, 23))
        self.kill_job_btn.setObjectName("kill_job_btn")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.find_job_btn.setText(_translate("Dialog", "Find Job"))
        self.label_job.setText(_translate("Dialog", "Job Name (exact):"))
        self.label_2.setText(_translate("Dialog", "Job ID:"))
        self.job_id.setText(_translate("Dialog", "ID"))
        self.mac_total.setText(_translate("Dialog", "MAC"))
        self.label_5.setText(_translate("Dialog", "Total Machines:"))
        self.com_total.setText(_translate("Dialog", "COM"))
        self.label_7.setText(_translate("Dialog", "Total Commands:"))
        self.kill_job_btn.setText(_translate("Dialog", "Kill Job"))
        self.pushButton.setText(_translate("Dialog", "Kill Batch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
